---
- name: Gather EOS configuration
  eos_command:
    commands: 'show running-config all'
    provider: "{{ provider|default(omit) }}"
    auth_pass: "{{ auth_pass|default(omit) }}"
    authorize: "{{ authorize|default(omit) }}"
    host: "{{ host|default(omit) }}"
    password: "{{ password|default(omit) }}"
    port: "{{ port|default(omit) }}"
    transport: 'cli'
    use_ssl: "{{ use_ssl|default(omit) }}"
    username: "{{ username|default(omit) }}"
  register: output
  no_log: "{{ no_log|default(true) }}"
  when: _eos_config is not defined

- name: Save EOS configuration
  set_fact:
    _eos_config: "{{ output.stdout[0] }}"
  no_log: "{{ no_log|default(true) }}"
  when: _eos_config is not defined

- name: Arista EOS BGP resources
  eos_template:
    src: bgp.j2
    include_defaults: true
    config: "{{ _eos_config | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    transport: 'cli'
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  register: bgp_result
  when: bgp is defined and bgp.bgp_as is defined

- block:
  # If the bgp task resulted in a change, we need to update
  # _eos_config, otherwise we may get unintended results
  # on future tasks

  - name: Gather EOS configuration
    eos_command:
      commands: 'show running-config all'
      provider: "{{ provider|default(omit) }}"
      auth_pass: "{{ auth_pass|default(omit) }}"
      authorize: "{{ authorize|default(omit) }}"
      host: "{{ host|default(omit) }}"
      password: "{{ password|default(omit) }}"
      port: "{{ port|default(omit) }}"
      transport: 'cli'
      use_ssl: "{{ use_ssl|default(omit) }}"
      username: "{{ username|default(omit) }}"
    register: output
    no_log: "{{ no_log|default(true) }}"

  - name: Save EOS configuration
    set_fact:
      _eos_config: "{{ output.stdout[0] }}"
    no_log: "{{ no_log|default(true) }}"

  when: bgp_result | changed

- block:
  # only do the remaining tasks if bgp was defined and present,
  # otherwise the configuration is pointless

  - name: Arista EOS BGP configure neighbors
    eos_template:
      src: bgp_neighbors.j2
      include_defaults: true
      config: "{{ _eos_config | default(omit) }}"
      auth_pass: "{{ auth_pass | default(omit) }}"
      authorize: "{{ authorize | default(omit) }}"
      host: "{{ host | default(omit) }}"
      password: "{{ password | default(omit) }}"
      port: "{{ port | default(omit) }}"
      provider: "{{ provider | default(omit) }}"
      transport: 'cli'
      use_ssl: "{{ use_ssl | default(omit) }}"
      username: "{{ username | default(omit) }}"
    when: bgp.enable is defined and bgp.enable and item.name is defined
    with_items: "{{ bgp.neighbors | default([]) }}"

  - name: Arista EOS BGP purge neighbors
    eos_template:
      src: bgp_purge_neighbors.j2
      include_defaults: true
      config: "{{ _eos_config | default(omit) }}"
      auth_pass: "{{ auth_pass | default(omit) }}"
      authorize: "{{ authorize | default(omit) }}"
      host: "{{ host | default(omit) }}"
      password: "{{ password | default(omit) }}"
      port: "{{ port | default(omit) }}"
      provider: "{{ provider | default(omit) }}"
      transport: 'cli'
      use_ssl: "{{ use_ssl | default(omit) }}"
      username: "{{ username | default(omit) }}"
    when: bgp.enable is defined and bgp.enable and eos_purge_bgp_neighbors

  - name: Arista EOS BGP redistribute setting
    eos_template:
      src: bgp_redistribute.j2
      include_defaults: true
      config: "{{ _eos_config | default(omit) }}"
      auth_pass: "{{ auth_pass | default(omit) }}"
      authorize: "{{ authorize | default(omit) }}"
      host: "{{ host | default(omit) }}"
      password: "{{ password | default(omit) }}"
      port: "{{ port | default(omit) }}"
      provider: "{{ provider | default(omit) }}"
      transport: 'cli'
      use_ssl: "{{ use_ssl | default(omit) }}"
      username: "{{ username | default(omit) }}"
    when: bgp.enable is defined and bgp.enable

  - name: Arista EOS BGP configure networks
    eos_template:
      src: bgp_networks.j2
      include_defaults: true
      config: "{{ _eos_config | default(omit) }}"
      auth_pass: "{{ auth_pass | default(omit) }}"
      authorize: "{{ authorize | default(omit) }}"
      host: "{{ host | default(omit) }}"
      password: "{{ password | default(omit) }}"
      port: "{{ port | default(omit) }}"
      provider: "{{ provider | default(omit) }}"
      transport: 'cli'
      use_ssl: "{{ use_ssl | default(omit) }}"
      username: "{{ username | default(omit) }}"
    when: bgp.enable is defined and bgp.enable
    with_items: "{{ bgp.networks | default([]) }}"

  - name: Arista EOS BGP purge networks
    eos_template:
      src: bgp_purge_networks.j2
      include_defaults: true
      config: "{{ _eos_config | default(omit) }}"
      auth_pass: "{{ auth_pass | default(omit) }}"
      authorize: "{{ authorize | default(omit) }}"
      host: "{{ host | default(omit) }}"
      password: "{{ password | default(omit) }}"
      port: "{{ port | default(omit) }}"
      provider: "{{ provider | default(omit) }}"
      transport: 'cli'
      use_ssl: "{{ use_ssl | default(omit) }}"
      username: "{{ username | default(omit) }}"
    when: bgp.enable is defined and bgp.enable and eos_purge_bgp_networks

  when: bgp is defined and bgp.bgp_as is defined
